SET SERVEROUTPUT ON;

ACCEPT profile_code NUMBER PROMPT 'Ingrese Codigo del Perfil Administrador: '
ACCEPT user_code NUMBER PROMPT 'Ingrese Codigo del Usuario Admin: '

DECLARE
	V_COUNT NUMBER;
	V_PROP_LEGACY NUMBER;
	K_PROFILE CONSTANT NUMBER := &profile_code;
    K_USER CONSTANT NUMBER := &user_code;

BEGIN
	V_PROP_LEGACY := 1;
	
	IF V_PROP_LEGACY = 1 THEN
		EXECUTE IMMEDIATE 'SELECT COUNT(1) FROM GRUP_USRS WHERE CODIGO_GRUP_USRS = :1' INTO V_COUNT USING K_PROFILE;
		IF V_COUNT = 0 THEN
			EXECUTE IMMEDIATE 'INSERT INTO GRUP_USRS (ID_GRUP_USRS,CODIGO_GRUP_USRS,NOMBRE_GRUP_USRS,ESTADO_GRUP_USRS) 
				VALUES ('|| K_PROFILE ||','|| K_PROFILE ||',''ADMINISTRADOR'',''1'')';
			DBMS_OUTPUT.PUT_LINE('INFO: Grupo ADMINISTRADOR creado con codigo ' || K_PROFILE);
		END IF;
		
		EXECUTE IMMEDIATE 'SELECT COUNT(1) FROM USRS WHERE CODIGO_USRS = :1' INTO V_COUNT USING K_USER;
		IF V_COUNT = 0 THEN
			EXECUTE IMMEDIATE 'INSERT INTO USRS (ID_USRS,ID_GRUP_USRS,ID_ESTA,ID_HUEL,ID_FOTO,ID_TISC,CODIGO_USRS,NOMBRE_USRS,APELLIDO_USRS,ESTADO_USRS,CLAVE_USRS,PWD_FECHA,ESTA_CCO) 
				VALUES ('|| K_USER ||','|| K_PROFILE ||',0,null,null,null,'|| K_USER ||',''USUARIO'',''ADMIN'',''1'',''ICy5YqxZB1uWSwcVLSNLcA=='',CURRENT_TIMESTAMP,null)';
				DBMS_OUTPUT.PUT_LINE('INFO: Usuario ADMIN creado con codigo ' || K_USER);
		END IF;

	ELSE
	
		EXECUTE IMMEDIATE 'SELECT COUNT(1) FROM PROFILES WHERE PROFILE_ID = :1' INTO V_COUNT USING K_PROFILE;
		IF V_COUNT = 0 THEN
			EXECUTE IMMEDIATE 'INSERT INTO PROFILES (PROFILE_ID,NAME,STATE) 
				VALUES (1,''DEFAULT'',''1'')';
			DBMS_OUTPUT.PUT_LINE('INFO: Perfil DEFAULT creado con codigo ' || K_PROFILE);
		END IF;
		
		EXECUTE IMMEDIATE 'SELECT COUNT(1) FROM USERS WHERE USER_ID = :1' INTO V_COUNT USING K_PROFILE;
		IF V_COUNT = 0 THEN
			EXECUTE IMMEDIATE 'INSERT INTO USERS (USER_ID,FIRST_NAME,LAST_NAME,STATE,PROFILE_ID,TOLL_ID) 
				VALUES (147,''USER'',''DEFAULT'',1,1,0)';
			EXECUTE IMMEDIATE 'INSERT INTO CREDENTIALS (CREDENTIAL_ID,USER_ID,PASSWORD,PSSW_DATE)
				VALUES (147,147,''{bcrypt}$2a$10$8KognaOLsCTIm35zajP6Su.N8FSUjvNCayUY1FBEVWaeeNkJytiDa'',CURRENT_TIMESTAMP)';
			DBMS_OUTPUT.PUT_LINE('INFO: Usuario DEFAULT creado con codigo ' || K_USER);
		END IF;

	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM AUTHORIZATIONS WHERE PROFILE_ID = K_PROFILE;
	IF V_COUNT = 0 THEN
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0001000100000001','281479271677953',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0001000100000002','281479271677954',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0001000100000004','281479271677956',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0001000100000008','281479271677960',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0001000100000010','281479271677968',K_PROFILE,null);

		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000100000001','562954248388609',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000100000004','562954248388612',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000200000001','562958543355905',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000200000004','562958543355908',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000200000010','562958543355920',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000200000020','562958543355936',K_PROFILE,null);
		INSERT INTO AUTHORIZATIONS (AUTHORIZATION_ID,RESOURCE_ID,PROFILE_ID,AUDIENCE_ID) VALUES (K_PROFILE||'0002000200000040','562958543355968',K_PROFILE,null);
		DBMS_OUTPUT.PUT_LINE('INFO: Permisos de acceso iniciales asignados al perfil con codigo ' || K_PROFILE);
    ELSE 
        DBMS_OUTPUT.PUT_LINE('INFO: Ya existen permisos asignados');
	END IF;
	COMMIT;
END;
