# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
      - us/*
  paths:
    exclude:
      - CICD
    include:
      - frontend
      - backend
      - database

stages:
- stage: BuildSettingsUsers
  displayName: Build stage FrontEnd BackEnd
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'Install users-app'
      inputs:
        command: 'install'
        workingDir: 'frontend/users-app'
        customRegistry: 'useFeed'
        customFeed: '193aea28-bf59-44f7-8801-5586babc21c0'
    
    - task: Npm@1
      displayName: 'npm Build'
      inputs:
        command: 'custom'
        workingDir: 'frontend/users-app'
        customCommand: 'run build:single-spa'
        customRegistry: 'useFeed'
        customFeed: '193aea28-bf59-44f7-8801-5586babc21c0'
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'backend/manager/pom.xml'
        options: '-DskipITs -X -Pprod'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: CopyFiles@2
      displayName: 'Copy Service Files'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/application'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/application'
        OverWrite: false
        
    - task: CopyFiles@2
      displayName: 'Copy Scripts'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/database'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/application/database'
        OverWrite: false        
        
    - task: CopyFiles@2
      displayName: 'Copy Documents'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/docs'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/docs'
        OverWrite: false            

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildNumber).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildNumber).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      enabled: true

#- stage: BuildBackEnd
#  displayName: Build stage BackEnd
##  jobs:
#  - job: BuildJob
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
